update docker-compose.ym, Dockerfile, pnpm-lock.yaml

diff --git a/leetnode/Dockerfile b/leetnode/Dockerfile
--- a/leetnode/Dockerfile
+++ b/leetnode/Dockerfile
@@ -1,12 +1,17 @@
 # syntax=docker/dockerfile:1.4
 
-FROM node:18-alpine AS base
+FROM node:18-alpine3.18 AS BASE
 WORKDIR /app
 
 # Install dependencies only when needed
 FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-RUN apk add --no-cache libc6-compat
+RUN apk add --no-cache libc6-compat \
+  vips-dev \
+  fftw-dev \
+  build-base \
+  python3
+
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
@@ -15,10 +20,14 @@ COPY --link /src/packages/mantine-rte /app/src/packages/mantine-rte
 COPY --link /prisma /app/prisma
 RUN \
   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm@7.23.0 && pnpm i --prod --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
+  elif [ -f package-lock.json ]; then npm ci --verbose --force; \
+  elif [ -f pnpm-lock.yaml ]; then \
+    yarn global add pnpm@7.23.0 && \
+    pnpm i --prod --frozen-lockfile; \
+  else \
+    echo "Lockfile not found." && exit 1; \
   fi
+
 
 # Rebuild the source code only when needed
 FROM base AS builder
@@ -27,7 +36,7 @@ COPY --from=deps --link /app/node_modules ./node_modules
 COPY --link . .
 
 ENV NEXT_TELEMETRY_DISABLED 1
-
+# RUN yarn add sharp --ignore-scripts
 RUN yarn build
 
 # Production image, copy all the files and run next
